# Generated by Django 5.0.7 on 2024-08-10 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='core.product'),
        ),
    ]
